server {
    listen 80 default_server;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location ^~ /login {
        proxy_pass http://healthtech.railway.internal:8000;
    }

    location ^~ /logout {
        proxy_pass http://healthtech.railway.internal:8000;
    }

    location ^~ /cadastrar {
        proxy_pass http://healthtech.railway.internal:8000;
    }

    location ^~ /alterar-senha {
        proxy_pass http://healthtech.railway.internal:8000;
    }

    location ^~ /atualizar-email {
        proxy_pass http://healthtech.railway.internal:8000;
    }

    location ^~ /admin {
        proxy_pass http://healthtech.railway.internal:8000;
    }

    location ^~ /resumos {
        proxy_pass http://healthtech.railway.internal:8000;
    }

    location ^~ /avaliar {
        proxy_pass http://healthtech.railway.internal:8000;
    }

    location ^~ /avaliacoes {
        proxy_pass http://healthtech.railway.internal:8000;
    }

    location ^~ /pdfs {
        proxy_pass http://healthtech.railway.internal:8000;
    }

    location ^~ /pdf {
        proxy_pass http://healthtech.railway.internal:8000;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}